name: Benchmarks

on:
  pull_request:
    branches:
      - main

jobs:
  create_droplet:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Prepare user-data file
        run: ./prepare-benchmark-userdata.sh
      - name: Create droplet
        run: doctl compute droplet create $GITHUB_SHA --size g-2vcpu-8gb --image rockylinux-9-x64 --user-data-file ./benchmark-setup.yml
